-- Generate the Neovim colorscheme and the ghostty theme from one source file.
--
--   nvim -l scripts/gen-theme.lua [theme] [--install]
--
-- theme      name of a file in theme/ (default: deepblue)
-- --install  also copy the ghostty theme into ~/.config/ghostty/themes/, then
--            enable it with `theme = <name>` in your ghostty config.
--
-- Outputs (both are generated, edit theme/<name>.lua instead):
--   colors/<name>.lua          :colorscheme <name>
--   extras/ghostty/<name>      ghostty theme

local root = vim.fs.dirname(vim.fs.dirname(vim.fs.normalize(vim.fn.fnamemodify(arg[0], ":p"))))

local name, install = "deepblue", false
for _, a in ipairs(arg) do
  if a == "--install" then
    install = true
  elseif not a:match("^%-") then
    name = a
  end
end

local theme = dofile(root .. "/theme/" .. name .. ".lua")

local function write(path, text)
  vim.fn.mkdir(vim.fs.dirname(path), "p")
  local f = assert(io.open(path, "w"))
  f:write(text)
  f:close()
  print("wrote " .. path)
end

-- Neovim --------------------------------------------------------------------

local groups = vim.tbl_keys(theme.hl)
table.sort(groups)

local lines = {
  "-- Generated by scripts/gen-theme.lua from theme/" .. name .. ".lua. Do not edit.",
  "vim.cmd('highlight clear')",
  "vim.g.colors_name = " .. vim.inspect(name),
  "vim.o.background = " .. vim.inspect(theme.background),
  "local hl = vim.api.nvim_set_hl",
}
for _, group in ipairs(groups) do
  table.insert(lines, ("hl(0, %q, %s)"):format(group, vim.inspect(theme.hl[group], { newline = " ", indent = "" })))
end
for i, color in ipairs(theme.ansi) do
  table.insert(lines, ("vim.g.terminal_color_%d = %q"):format(i - 1, color))
end
write(root .. "/colors/" .. name .. ".lua", table.concat(lines, "\n") .. "\n")

-- ghostty -------------------------------------------------------------------

local t = theme.terminal
local ghostty = { "# Generated by nvim scripts/gen-theme.lua from theme/" .. name .. ".lua." }
for i, color in ipairs(theme.ansi) do
  table.insert(ghostty, ("palette = %d=%s"):format(i - 1, color))
end
vim.list_extend(ghostty, {
  "background = " .. t.background,
  "foreground = " .. t.foreground,
  "cursor-color = " .. t.cursor,
  "cursor-text = " .. t.cursor_text,
  "selection-background = " .. t.selection_bg,
  "selection-foreground = " .. t.selection_fg,
})
local ghostty_text = table.concat(ghostty, "\n") .. "\n"
write(root .. "/extras/ghostty/" .. name, ghostty_text)

if install then
  local dir = (vim.env.XDG_CONFIG_HOME or (vim.env.HOME .. "/.config")) .. "/ghostty/themes"
  write(dir .. "/" .. name, ghostty_text)
  print(("add `theme = %s` to your ghostty config and reload the ghostty config"):format(name))
end
